// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1W7_z8nn6zEcAQJ3nYieYKD-UQE6w3Z0',
    appId: '1:984562508992:web:9c0c5da83078009992f925',
    messagingSenderId: '984562508992',
    projectId: 'authproj-24970',
    authDomain: 'authproj-24970.firebaseapp.com',
    storageBucket: 'authproj-24970.firebasestorage.app',
    measurementId: 'G-T0S7SKEDVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbd2pduc5VRQnEdzEjEukUWpNBKesceuU',
    appId: '1:984562508992:android:dfac02608ac30a9f92f925',
    messagingSenderId: '984562508992',
    projectId: 'authproj-24970',
    storageBucket: 'authproj-24970.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0vRsQ3rf84sCp4UBotrg3WL4N34qE0-M',
    appId: '1:984562508992:ios:c048aa1c5f651c6492f925',
    messagingSenderId: '984562508992',
    projectId: 'authproj-24970',
    storageBucket: 'authproj-24970.firebasestorage.app',
    iosBundleId: 'com.example.g3Autenticacion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0vRsQ3rf84sCp4UBotrg3WL4N34qE0-M',
    appId: '1:984562508992:ios:c048aa1c5f651c6492f925',
    messagingSenderId: '984562508992',
    projectId: 'authproj-24970',
    storageBucket: 'authproj-24970.firebasestorage.app',
    iosBundleId: 'com.example.g3Autenticacion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1W7_z8nn6zEcAQJ3nYieYKD-UQE6w3Z0',
    appId: '1:984562508992:web:38718179a702f6c892f925',
    messagingSenderId: '984562508992',
    projectId: 'authproj-24970',
    authDomain: 'authproj-24970.firebaseapp.com',
    storageBucket: 'authproj-24970.firebasestorage.app',
    measurementId: 'G-Z6XEYY3F5V',
  );
}
